-- MySQL Script generated by MySQL Workbench
-- Thu Sep 17 18:45:15 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `biblioteca` DEFAULT CHARACTER SET utf8 ;
USE `biblioteca` ;

-- -----------------------------------------------------
-- Table `mydb`.`USUARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `USUARIO` (
  `id_usuario` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NULL,
  `senha` VARCHAR(45) NULL,
  `quantidade_livros` INT NULL,
  PRIMARY KEY (`id_usuario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`LIVRO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `LIVRO` (
  `id_livro` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  `autor` VARCHAR(45) NULL,
  `editora` VARCHAR(45) NULL,
  PRIMARY KEY (`id_livro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EMPRESTIMO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `EMPRESTIMO` (
  `id_emprestimo` INT NOT NULL AUTO_INCREMENT,
  `data_retirada` DATETIME NULL,
  `data_entrega` DATETIME NULL,
  `renovacao` TINYINT NULL,
  `status` TINYINT NULL,
  `id_livro` INT NOT NULL,
  `id_usuario` INT NOT NULL,
  PRIMARY KEY (`id_emprestimo`, `id_livro`, `id_usuario`),
  INDEX `fk_Emprestimo_Livro1_idx` (`id_livro` ASC) VISIBLE,
  INDEX `fk_EMPRESTIMO_USUARIO1_idx` (`id_usuario` ASC) VISIBLE,
  CONSTRAINT `fk_Emprestimo_Livro1`
    FOREIGN KEY (`id_livro`)
    REFERENCES `LIVRO` (`id_livro`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_EMPRESTIMO_USUARIO1`
    FOREIGN KEY (`id_usuario`)
    REFERENCES `USUARIO` (`id_usuario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
